### ISSUE TITLE
Can I get some details about source code?

### ISSUE THREAD

**Issue by git-jhyang** [wufan2021/Heterogeneous-Graph-Information-Bottleneck#2]
I interestingly read your paper "Heterogeneous graph information bottleneck" and found this github through google search.

I want to apply your idea, sharing information between graphs, to my model.

But.. I got some trouble to understand your code, especially on calculating mutual information.

In your code, MIEstimator, there just a dense network with ReLU activation, and returning softplus of "pos" and "neg", and with some operation of them.

I found several codes for calculating MI (mutual information) through web, and they calculated entropies and/or probability densities.

But I can not found that part in your code.

I think returning value of MIEstimator have some mathmatical meaning but I cannot understand.

Can you give some insight about MI in your code?

**Comment by wufan-llm** [comment]
计算互信息的具体思路你可以参考文章Mutual Information Neural Estimation，大体上是说如何使用神经网络来「估计」互信息

**Comment by git-jhyang** [comment]
can you give me some references?

**Comment by git-jhyang** [comment]
you mean this paper?

https://arxiv.org/abs/1801.04062
